### ISSUE TITLE
Allow network AI

### ISSUE THREAD

**Issue by UnsolvedCypher** [jwestp/docker-supertuxkart#3]
It would be great to be able to specify the number of network AI. Perhaps it could be specified as an environment variable?

**Comment by iluvatyr** [comment]
You can do it if you started up the docker once, you can stop the container and then run following commands. You can also put them into a bash script if you like. Its not the optimum solution, but for me it works like that til now. You may have to change IP and port aswell as $supertuxcontainer.

docker container exec $supertuxcontainer supertuxkart --connect-now=127.0.0.1:2759 --network-ai=2 &

**Comment by jwestp** [comment]
Network ai can now be configured with the environment variable `AI_KARTS`. See the updated README for details.
