### ISSUE TITLE
Server running and being found from game, but cant join

### ISSUE THREAD

**Issue by iluvatyr** [jwestp/docker-supertuxkart#6]
Hello, I just came across your project and instantly thought its pretty cool someone made this. I tried to run the server within my server as a Docker container and it works flawlessly to start it. I can also see the server when browsing through servers. The necessary ports are forwarded correctly. Yet when I click on the server with my Client it doesnt connect to the server. My logs are shown below (only last entrys are important I guess). Any Idea why this might be happening? Do I miss some configuration?

Second thing is: is it possible to choose the location of the root folder, especially where all the data for high scores etc. is stored so that it is possible to delete the container and service and just redeploy with a volume where all the configs are stored?

root@6ad81f03bf92:~/.config/supertuxkart/config-0.10# cat server_config.log 
[info   ] [FileManager]: Data files will be fetched from: '/usr/local/share/supertuxkart/data/'
[info   ] [FileManager]: User directory is '/root/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/root/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/root/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/root/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from '/usr/local/share/supertuxkart/data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from '/usr/local/share/supertuxkart/data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from '/usr/local/share/supertuxkart/data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from '/usr/local/share/supertuxkart/data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from '/usr/local/share/supertuxkart/data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from '/usr/local/share/supertuxkart/data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from '/usr/local/share/supertuxkart/data/replay/'.
[info   ] [FileManager]: Asset 7 will be loaded from '/usr/local/share/supertuxkart/data/shaders/'.
[info   ] [FileManager]: Asset 8 will be loaded from '/usr/local/share/supertuxkart/data/skins/'.
[info   ] [FileManager]: Asset 9 will be loaded from '/usr/local/share/supertuxkart/data/ttf/'.
[info   ] [FileManager]: Asset 10 will be loaded from '/usr/local/share/supertuxkart/data/po/'.
[info   ] [FileManager]: Asset 11 will be loaded from '/usr/local/share/supertuxkart/data/library/'.
[info   ] [FileManager]: Asset 12 will be loaded from '/usr/local/share/supertuxkart/data/models/'.
[info   ] [FileManager]: Asset 13 will be loaded from '/usr/local/share/supertuxkart/data/music/'.
[info   ] [FileManager]: Asset 14 will be loaded from '/usr/local/share/supertuxkart/data/sfx/'.
[info   ] [FileManager]: Asset 15 will be loaded from '/usr/local/share/supertuxkart/data/textures/'.
[info   ] [FileManager]: Asset 16 will be loaded from '/usr/local/share/supertuxkart/data/tracks/'.
[info   ] HTTPRequest: Sending userid=267631&token=************************ to https://online.supertuxkart.net/api/v2/user/saved-session/
[info   ] GrandPrixManager: Loading Grand Prix files from /usr/local/share/supertuxkart/data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /root/.local/share/supertuxkart/grandprix/
[info   ] Achievements: Synching achievement 1,2,3,4,5,7,9,11 to server.
[info   ] HTTPRequest: Sending userid=267631&token=************************&achievementid=1%2C2%2C3%2C4%2C5%2C7%2C9%2C11 to https://online.supertuxkart.net/api/v2/user/achieving/
Tue May 11 13:20:27 2021 [info   ] STKHost: Host initialized.
Tue May 11 13:20:27 2021 [info   ] STKHost: Server port is 2759
Tue May 11 13:20:27 2021 [info   ] ServerLobby: Resetting the server to its initial state.
Tue May 11 13:20:27 2021 [info   ] ProtocolManager: A 11ServerLobby protocol has been started.
Tue May 11 13:20:27 2021 [info   ] main: Creating a WAN server 'Testserver12345'.
Tue May 11 13:20:27 2021 [warn   ] LayoutManager: Widget 'timeout-message' has a height of 0 (left_space = 0, fraction = 1.000000, max_width = )

Tue May 11 13:20:28 2021 [info   ] HTTPRequest: Sending userid=267631&token=************************&visitingid=267631 to https://online.supertuxkart.net/api/v2/user/get-friends-list/
Tue May 11 13:20:28 2021 [info   ] STKHost: Listening has been started.
Tue May 11 13:20:28 2021 [info   ] ServerLobby: Public server address <MyPublicIP>:2759
Tue May 11 13:20:28 2021 [info   ] HTTPRequest: Sending userid=245632&token=************************&address=1486544844832673&port=2759&private_port=2759&name=Testserver12345&max_players=8&difficulty=0&game_mode=3&password=*&version=6 to https://online.supertuxkart.net/api/v2/server/create/

Tue May 11 13:20:28 2021 [info   ] ServerLobby: Server 301096 is now online.
Tue May 11 13:30:03 2021 [info   ] ProtocolManager: A 13ConnectToPeer protocol has been started.
Tue May 11 13:30:25 2021 [warn   ] ConnectToPeer: Time out trying to connect to 46.114.108.132:9760
Tue May 11 13:30:25 2021 [info   ] ProtocolManager: A 13ConnectToPeer protocol has been terminated.

**Comment by jwestp** [comment]
Hi Luca!

Are you hosting your server locally or on a VPS? If you configured the server to be a wan server and correctly forwarded all the required ports it should work just fine. Did you try connecting with different clients to ensure it is not a problem with your specific connection?

> Second thing is: is it possible to choose the location of the root folder, especially where all the data for high scores etc. is stored so that it is possible to delete the container and service and just redeploy with a volume where all the configs are stored?

Since the files you mention are all stored in `/root/.config/supertuxkart/config-0.10` you can easily mount this as a volume into your container. Just add something like this to your `docker run` command:

`-v $(pwd)/my-data-dir:/root/.config/supertuxkart/config-0.10`

**Comment by iluvatyr** [comment]
Hey, sorry for late reply and thanks for your answer! 
Im hosting on my private server. Set the variable for WAN-Server in server-config.xml so that its a WAN server. I tried connecting from different clients aswell. Somehow I see the server, but when I click on it, nothing really happens until the timeout. I forwarded all ports (2757 and 2759) to the server running the supertuxkarts-server. Can this problem occur if there are not enough system resources available? What are the minimum resources to be able to run the server?

as for the mount it as a volume. Thanks for the reply. This works!

**Comment by jwestp** [comment]
I’m sorry that it doesn’t work for you. I once again tried hosting the container on different servers and it always worked as expected. I have no idea what could be the reason for the timeout… Regarding system resources the smallest machine I used was a virtual server with a single core and 2 GB RAM.

**Comment by iluvatyr** [comment]
> I’m sorry that it doesn’t work for you. I once again tried hosting the container on different servers and it always worked as expected. I have no idea what could be the reason for the timeout… Regarding system resources the smallest machine I used was a virtual server with a single core and 2 GB RAM.

I figured it out. It is necessary to use the host network for it to work apparently. Adding "    network_mode: host" and it works.
```
---
version: "3.8"
services:
  supertuxkart-server:
    image: jwestp/supertuxkart:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /srv/dev-disk-by-label-Data/Config/Supertux/server_config.xml:/stk/server_config.xml
      - /srv/dev-disk-by-label-Data/Config/Supertux/:/root/.config/supertuxkart/config-0.10
    environment:
      - USERNAME=Luva9497
      - PASSWORD=legolas1
      - PUID=998
      - PGID=100
    ports:
      - "2757:2757"
      - "2759:2759"
```

**Comment by jwestp** [comment]
Using the host network driver should usually not be necessary but good to hear that the problem is solved for you now. :+1:
